### ISSUE TITLE
Allow user to set default config

### ISSUE THREAD

**Issue by rzlnhd** [srexi/purecounterjs#14]
Hai... I've an idea to allow users set their default config, so they doesn't need to set `data-purecounter-X` to each element for the same config.

So instead of just initialize the `Purecounter` class, it also can initialize the default config. If users doesn't initialize `their config`, it will use `our default config`. What do you think?

Also, I think you should update the npm package. It's too old by the way...

**Comment by srexi** [comment]
Yes it is too old I've set some time aside here during next week to update it.
Yeah ideally it would merge the Purecounter default config with the provided initial values.
That sounds like a great idea

**Comment by srexi** [comment]
Fixed #26
