### ISSUE TITLE
Version does not match current tag

### ISSUE THREAD

**Issue by williamdes** [srexi/purecounterjs#19]
https://github.com/srexi/purecounterjs/blob/b0668b1f15310189577b0ccee5285c44790a99ab/dist/purecounter.js#L4

Seems like it would need a bump before making a tag :)

**Comment by srexi** [comment]
fixed thanks:
https://github.com/srexi/purecounterjs/commit/cbf4b034cba3391cd3d40855fd1433f7703baa74

**Comment by williamdes** [comment]
Could you re-build bundle files and publish a tag please ?

**Comment by williamdes** [comment]
My point is that the version people will download using tag 1.2.0 will say version 1.1.4 and it will confuse people ;)
(on bundle files)

**Comment by williamdes** [comment]
Maybe just delete tag 1.2.1 and publish it back after bundle update :)

I can make a PR if you do not have the repo locally ready

**Comment by srexi** [comment]
Yeah I think this will do for now
