### ISSUE TITLE
Commas

### ISSUE THREAD

**Issue by digourideas** [srexi/purecounterjs#2]
It appears that using any number besides numbers that end in 0 ex, 9,000 or 4,000 - Don't keep their commas when landing on the final number.  Is there a way to keep the commas in the number?

**Comment by srexi** [comment]
Yes I will work on a fix for that tomorrow. Thanks for reporting it in! :)

**Comment by srexi** [comment]
Did you set the data-purecounter-decimals="n" property ? n being the number of decimals you'd like to keep.

Here's an example that worked for me:
`
<span data-purecounter-decimals="2" data-purecounter-start="0" data-purecounter-end="9000.01" data-purecounter-duration="2" class="purecounter" >0</span>`

A possible improvement would be to have a setting to: simply write down your end number no matter what the decimal formatting is. However that's just even more properties that needs to be understood in my opinion.

**Comment by srexi** [comment]
Closing as this is stale, feel free to open again
