### ISSUE TITLE
does not seem to be working in React (typescript)

### ISSUE THREAD

**Issue by poplevente** [srexi/purecounterjs#24]
at build:
Could not find a declaration file for module '@srexi/purecounterjs'. 'node_modules/@srexi/purecounterjs/dist/purecounter.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/srexi__purecounterjs` if it exists or add a new declaration (.d.ts) file containing `declare module '@srexi/purecounterjs';

could be nice to fix

**Comment by srexi** [comment]
Totally open for PR regarding this.

**Comment by srexi** [comment]
Please let us know if #26 resolves it for you @poplevente

**Comment by srexi** [comment]
closed due to inactivity
