### ISSUE TITLE
1.3.0 CDN not working.

### ISSUE THREAD

**Issue by spicehoarder** [srexi/purecounterjs#29]
I'm not really sure what's different in the latest CDN, but I've had to revert back to 1.2.1
This is what I'm working with:

```
<span data-purecounter-start="0" data-purecounter-end="10" data-purecounter-duration="1" class="purecounter"></span>

<script src="https://cdn.jsdelivr.net/npm/@srexi/purecounterjs/dist/purecounter_vanilla.js"></script>
```

**Comment by srexi** [comment]
Hey @spicehoarder can you describe what's happening?
Are you getting any errors in the console?

**Comment by rzlnhd** [comment]
![image](https://user-images.githubusercontent.com/43670693/151930287-88600c0a-faf7-491b-af18-29cb0a3a33cb.png)
@srexi I think the problem is on your build workflow sir. There is no return function here.

**Comment by srexi** [comment]
I think you're right!
try this @spicehoarder https://cdn.jsdelivr.net/npm/@srexi/purecounterjs@1.4.1/dist/purecounter_vanilla.js
