### ISSUE TITLE
data-purecounter-duration doesn't seem to work

### ISSUE THREAD

**Issue by timrj** [srexi/purecounterjs#3]
I am using this code:

`<span data-purecounter-duration="20.5" data-purecounter-end="15" class="purecounter">0</span>`

But it doesn't matter what I put in the duration it still seems to complete within ~1 second.

Thanks.

**Comment by srexi** [comment]
I'll look into it, thanks for providing an example

**Comment by timrj** [comment]
I think I've figured out the issue now.

If you have a low number (e.g. 10) the standard duration is quicker than a longer number (e.g. 10,000). So if I have "10" and "10,000" running next to each other, "10,000" will take longer to finish animating.

Setting data-purecounter-duration slows down the duration of the above, but it's not standardised.

So if I set data-purecounter-duration="4000" on "10" it still completes almost instantly.
If I set data-purecounter-duration="4000" on "10,000" it takes a looooot longer to complete.

If there was a way to standardise the duration of the animation for any number before adding a duration, it would make the data-purecounter-duration work as expected.

I understand if this isn't possible. Thanks!

**Comment by srexi** [comment]
@timrj yes I agree that will be desirable. I'm thinking about how we can accomplish this. Thanks for the very detailed report

**Comment by beysim** [comment]
Hi, any update on this?
Also, the duration re-set to 0 if once is set to true

**Comment by srexi** [comment]
@beysim going to review the PR from @rzlnhd  tomorrow and push a fix.

**Comment by srexi** [comment]
Merged and fixed in #12
