### ISSUE TITLE
Numbers with a comma

### ISSUE THREAD

**Issue by timrj** [srexi/purecounterjs#4]
Hi, is there a way to display numbers with a comma, but no decimals?

Desired result: 10,000

without data-purecounter-decimals > 10000

data-purecounter-decimals="1" > 10,000.0 (closest to desired result)

data-purecounter-decimals="0" > 10000

Thanks.

**Comment by srexi** [comment]
Yes good idea @timrj

**Comment by timrj** [comment]
Thank you - I feel like data-purecounter-decimals="0" should make this outcome and "none" / "false" should be the default.

Cheers for the quick response.

**Comment by rzlnhd** [comment]
This issue already fixed.
