### ISSUE TITLE
Counter for long number

### ISSUE THREAD

**Issue by rzlnhd** [srexi/purecounterjs#7]
Hi... I just use this script for my web... But I have a problem when count a long number (i.e. million, billion, or trillion) in small place... Is it possible make it short (e.g. `1200000` become `1.2 M`)? Thank you.

**Comment by srexi** [comment]
Yes that sounds like an excellent idea.
Maybe with some option to set max amount of digits you'd want to show.

So 
max-digits=5
you could make it so it would write 99.999 but as soon as it goes 1 higher it would say 100k instead.

**Comment by srexi** [comment]
Implement feature by #8 
Thanks @rzlnhd
